services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/Application/**Command.php'
            - '../src/**/Domain/{Entity,Exception,Value}/*'
            - '../src/**/Infrastructure/{Exception,Value}/*'
            - '../src/**/Ui/Http/Rest/{Request,Response}/*'

    App\Message\Email\Application\SendEmailHandler:
        arguments:
            $sender: '%env(MAILER_SENDER)%'

    # Interface definitions:
    App\Benchmark\Infrastructure\Logger\Conversion\ReportConverter $logConverter:
        class: App\Benchmark\Infrastructure\Logger\Conversion\ReportToLogConverter\ReportToLogConverter

    App\Shared\Infrastructure\Logger\Logger $txtLogger:
        class: App\Shared\Infrastructure\Logger\TxtLogger\TxtLogger
        arguments:
            $logPath: '%kernel.root_dir%/../var/log/benchmark/log.txt'